-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-constel_note-cn_theme_unique.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX cn_theme;

CREATE UNIQUE INDEX cn_theme_unique ON constel_note (cn_theme);
