-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE constel_concept (
  cc_id SERIAL NOT NULL,
  cc_key TEXT NOT NULL,
  cc_fold TEXT NOT NULL,
  cc_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cc_id)
);

CREATE UNIQUE INDEX cc_key ON constel_concept (cc_key);

CREATE INDEX cc_fold ON constel_concept (cc_fold);


CREATE TABLE constel_excerpt (
  ce_id SERIAL NOT NULL,
  ce_actor BIGINT NOT NULL,
  ce_page INT NOT NULL,
  ce_rev INT NOT NULL,
  ce_exact TEXT NOT NULL,
  ce_prefix TEXT NOT NULL,
  ce_suffix TEXT NOT NULL,
  ce_start INT NOT NULL,
  ce_end INT NOT NULL,
  ce_gloss TEXT DEFAULT NULL,
  ce_status SMALLINT DEFAULT 0 NOT NULL,
  ce_created TIMESTAMPTZ NOT NULL,
  ce_lost TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(ce_id)
);

CREATE INDEX ce_page_status ON constel_excerpt (ce_page, ce_status);

CREATE INDEX ce_actor_created ON constel_excerpt (ce_actor, ce_created);


CREATE TABLE constel_coding (
  ccd_excerpt INT NOT NULL,
  ccd_concept INT NOT NULL,
  ccd_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ccd_excerpt, ccd_concept)
);

CREATE INDEX ccd_concept ON constel_coding (ccd_concept);


CREATE TABLE constel_theme (
  ct_id SERIAL NOT NULL,
  ct_actor BIGINT NOT NULL,
  ct_label TEXT NOT NULL,
  ct_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ct_id)
);

CREATE INDEX ct_actor ON constel_theme (ct_actor);


CREATE TABLE constel_membership (
  cm_actor BIGINT NOT NULL,
  cm_concept INT NOT NULL,
  cm_theme INT NOT NULL,
  PRIMARY KEY(cm_actor, cm_concept)
);

CREATE INDEX cm_theme ON constel_membership (cm_theme);

CREATE INDEX cm_concept ON constel_membership (cm_concept);


CREATE TABLE constel_note (
  cn_id SERIAL NOT NULL,
  cn_theme INT NOT NULL,
  cn_text TEXT NOT NULL,
  cn_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cn_id)
);

CREATE UNIQUE INDEX cn_theme_unique ON constel_note (cn_theme);
