-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-constel_excerpt-ce_gloss.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/constel_excerpt
  ADD COLUMN ce_gloss BLOB DEFAULT NULL;
