-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-constel_note-cn_theme_unique.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__constel_note AS
SELECT
  cn_id,
  cn_theme,
  cn_text,
  cn_updated
FROM /*_*/constel_note;
DROP TABLE /*_*/constel_note;


CREATE TABLE /*_*/constel_note (
    cn_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    cn_theme INTEGER UNSIGNED NOT NULL,
    cn_text BLOB NOT NULL, cn_updated BLOB NOT NULL
  );
INSERT INTO /*_*/constel_note (
    cn_id, cn_theme, cn_text, cn_updated
  )
SELECT
  cn_id,
  cn_theme,
  cn_text,
  cn_updated
FROM
  /*_*/__temp__constel_note;
DROP TABLE /*_*/__temp__constel_note;

CREATE UNIQUE INDEX cn_theme_unique ON /*_*/constel_note (cn_theme);
