-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/constel_concept (
  cc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cc_key BLOB NOT NULL, cc_fold BLOB NOT NULL,
  cc_created BLOB NOT NULL
);

CREATE UNIQUE INDEX cc_key ON /*_*/constel_concept (cc_key);

CREATE INDEX cc_fold ON /*_*/constel_concept (cc_fold);


CREATE TABLE /*_*/constel_excerpt (
  ce_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ce_actor BIGINT UNSIGNED NOT NULL,
  ce_page INTEGER UNSIGNED NOT NULL,
  ce_rev INTEGER UNSIGNED NOT NULL, ce_exact BLOB NOT NULL,
  ce_prefix BLOB NOT NULL, ce_suffix BLOB NOT NULL,
  ce_start INTEGER UNSIGNED NOT NULL,
  ce_end INTEGER UNSIGNED NOT NULL, ce_gloss BLOB DEFAULT NULL,
  ce_status SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  ce_created BLOB NOT NULL, ce_lost BLOB DEFAULT NULL
);

CREATE INDEX ce_page_status ON /*_*/constel_excerpt (ce_page, ce_status);

CREATE INDEX ce_actor_created ON /*_*/constel_excerpt (ce_actor, ce_created);


CREATE TABLE /*_*/constel_coding (
  ccd_excerpt INTEGER UNSIGNED NOT NULL,
  ccd_concept INTEGER UNSIGNED NOT NULL,
  ccd_timestamp BLOB NOT NULL,
  PRIMARY KEY(ccd_excerpt, ccd_concept)
);

CREATE INDEX ccd_concept ON /*_*/constel_coding (ccd_concept);


CREATE TABLE /*_*/constel_theme (
  ct_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ct_actor BIGINT UNSIGNED NOT NULL,
  ct_label BLOB NOT NULL, ct_created BLOB NOT NULL
);

CREATE INDEX ct_actor ON /*_*/constel_theme (ct_actor);


CREATE TABLE /*_*/constel_membership (
  cm_actor BIGINT UNSIGNED NOT NULL,
  cm_concept INTEGER UNSIGNED NOT NULL,
  cm_theme INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(cm_actor, cm_concept)
);

CREATE INDEX cm_theme ON /*_*/constel_membership (cm_theme);

CREATE INDEX cm_concept ON /*_*/constel_membership (cm_concept);


CREATE TABLE /*_*/constel_note (
  cn_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cn_theme INTEGER UNSIGNED NOT NULL,
  cn_text BLOB NOT NULL, cn_updated BLOB NOT NULL
);

CREATE INDEX cn_theme ON /*_*/constel_note (cn_theme);
