-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/constel_concept (
  cc_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cc_key VARBINARY(320) NOT NULL,
  cc_fold VARBINARY(320) NOT NULL,
  cc_created BINARY(14) NOT NULL,
  UNIQUE INDEX cc_key (cc_key),
  INDEX cc_fold (cc_fold),
  PRIMARY KEY(cc_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/constel_excerpt (
  ce_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ce_actor BIGINT UNSIGNED NOT NULL,
  ce_page INT UNSIGNED NOT NULL,
  ce_rev INT UNSIGNED NOT NULL,
  ce_exact BLOB NOT NULL,
  ce_prefix VARBINARY(255) NOT NULL,
  ce_suffix VARBINARY(255) NOT NULL,
  ce_start INT UNSIGNED NOT NULL,
  ce_end INT UNSIGNED NOT NULL,
  ce_gloss BLOB DEFAULT NULL,
  ce_status TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  ce_created BINARY(14) NOT NULL,
  ce_lost BINARY(14) DEFAULT NULL,
  INDEX ce_page_status (ce_page, ce_status),
  INDEX ce_actor_created (ce_actor, ce_created),
  PRIMARY KEY(ce_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/constel_coding (
  ccd_excerpt INT UNSIGNED NOT NULL,
  ccd_concept INT UNSIGNED NOT NULL,
  ccd_timestamp BINARY(14) NOT NULL,
  INDEX ccd_concept (ccd_concept),
  PRIMARY KEY(ccd_excerpt, ccd_concept)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/constel_theme (
  ct_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ct_actor BIGINT UNSIGNED NOT NULL,
  ct_label VARBINARY(320) NOT NULL,
  ct_created BINARY(14) NOT NULL,
  INDEX ct_actor (ct_actor),
  PRIMARY KEY(ct_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/constel_membership (
  cm_actor BIGINT UNSIGNED NOT NULL,
  cm_concept INT UNSIGNED NOT NULL,
  cm_theme INT UNSIGNED NOT NULL,
  INDEX cm_theme (cm_theme),
  INDEX cm_concept (cm_concept),
  PRIMARY KEY(cm_actor, cm_concept)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/constel_note (
  cn_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cn_theme INT UNSIGNED NOT NULL,
  cn_text MEDIUMBLOB NOT NULL,
  cn_updated BINARY(14) NOT NULL,
  INDEX cn_theme (cn_theme),
  PRIMARY KEY(cn_id)
) /*$wgDBTableOptions*/;
